
export const MONSTER_GREEN = '#71BE44';

export const INITIAL_FLAVORS: string[] = [
  "Monster Energy Original Green \"OG\"",
  "Monster Energy Zero Sugar",
  "Monster Energy Nitro Super Dry",
  "Monster Energy Lo‑Carb",
  "Monster Energy Electric Blue",
  "Monster Energy Orange Dreamsicle",
  "Monster Energy Strawberry Shot",
  "Monster Energy Lando Norris Edition",
  "Monster Energy Reserve Orange Dreamsicle",
  "Monster Energy Reserve Peaches n’ Crème",
  "Monster Energy Super‑Premium Import",
  "Ultra Zero Ultra (White)",
  "Ultra Wild Passion",
  "Ultra Blue Hawaiian",
  "Ultra Vice Guava",
  "Ultra Watermelon",
  "Ultra Strawberry Dreams",
  "Ultra Sunrise",
  "Ultra Peachy Keen",
  "Ultra Fantasy Ruby Red",
  "Ultra Rosá",
  "Ultra Red",
  "Ultra Blue",
  "Ultra Paradise",
  "Ultra Fiesta Mango",
  "Ultra Black",
  "Ultra Violet",
  "Java Monster Mean Bean",
  "Java Monster Irish Crème",
  "Java Monster Café Latte",
  "Java Monster 300 Mocha",
  "Java Monster 300 French Vanilla",
  "Java Monster Salted Caramel",
  "Killer Brew Loca Moca",
  "Killer Brew Mean Bean",
  "Juice Monster Bad Apple",
  "Juice Monster Mango Loco",
  "Juice Monster Viking Berry",
  "Juice Monster Rio Punch",
  "Juice Monster Pacific Punch",
  "Juice Monster Pipeline Punch",
  "Juice Monster Aussie Style Lemonade",
  "Juice Monster Khaotic",
  "Rehab Tea + Lemonade",
  "Rehab Green Tea",
  "Rehab Peach Tea",
  "Rehab Wild Berry Tea",
  "Rehab Strawberry Lemonade",
  "Monster Assault",
  "Monster Ripper",
  "Monster Cuba‑Libre",
  "Monster Dub Mad Dog",
  "Monster Maxx",
  "Monster Super‑Premium Import Light",
  "Monster Absolutely Zero",
  "Monster M‑80",
  "Monster Extra Strength M3",
  "Monster Super Cola"
];
